spring.application.name=sfa

spring.datasource.url=jdbc:postgresql://localhost:5432/social-feed-app
spring.datasource.username=sfa
spring.datasource.password=sfa123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

######## JWT Config #########
jwt.secret=12345678901234567890123456789012
jwt.expiration-ms=86400000
