spring.application.name=sfa

spring.datasource.url=jdbc:postgresql://localhost:5432/social-feed-app
spring.datasource.username=sfa
spring.datasource.password=sfa123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true